### ISSUE TITLE
Update Readme links 

### ISSUE THREAD

**Issue by Sibam-Paul** [Yeasir0032/Discord-Clone#11]
**Saw links on readme of texh used not linked **

**Picture reference**
![image](https://github.com/Yeasir0032/Discord-Clone/assets/158052549/7de72edf-ce24-4017-8d8d-efd7a0673d39)

_Please assign me this under GSsoc'24_

**Comment by Sibam-Paul** [comment]
Please assign it to link the Typescipr, node.js and socket Io to thier documentation page

**Comment by Yeasir0032** [comment]
I am assigning this to you. Before creating a pull request make sure you pull the changes to your forked one to avoid merge conflicts.

**Comment by Sibam-Paul** [comment]
Done

**Comment by Rv43** [comment]
Can you please assign me this issue to work with you
