### ISSUE TITLE
Gitignore file update

### ISSUE THREAD

**Issue by Yeasir0032** [Yeasir0032/Discord-Clone#13]
### Gitignore file - add .vscode directory to gitignore
In the [gitignore](https://github.com/Yeasir0032/Discord-Clone/blob/main/.gitignore) file add **.vscode** directory.

**Comment by 01Sriharsha** [comment]
@Yeasir0032 Can you assign this issue to me under GSSOC'24? I can update this.

**Comment by Yeasir0032** [comment]
Assigned to you.
