### ISSUE TITLE
Search option must be sticky

### ISSUE THREAD

**Issue by raghavawasthi24** [Yeasir0032/Discord-Clone#14]
Search option must be fixed at top. It should not be scrollable to make easy for users to search.

**Expected behavior**
Search bar will be sticky at the top and rest of the part scrollable.

**Screenshots**
![Screenshot (223)](https://github.com/Yeasir0032/Discord-Clone/assets/113261155/b8504ad6-ecb5-4a71-97eb-ad900257d4fa)

**Desktop (please complete the following information):**
 - OS:Windows
 - Browser Chrome

**Smartphone (please complete the following information):**
 - Device: Realme narzo 50A
 - OS: Android
 - Browser Chrome

**Comment by raghavawasthi24** [comment]
I can fix this. Can you assign me?

**Comment by Yeasir0032** [comment]
Okay This is a minor fix. 
I am giving it a level 1

**Comment by Aadityagoel15** [comment]
hey @Yeasir0032 
Can you also assign me this. I can also fix this

**Comment by Yeasir0032** [comment]
Hey @Aadityagoel15 sorry for that but I have assigned @raghavawasthi24 . It is better to go with first come first serve, isn't it.
You can checkout other issues or create a new one. 
There are many ui-ux fixes that need to be done, just look for it.
