### ISSUE TITLE
Creating a explore page for servers

### ISSUE THREAD

**Issue by Yeasir0032** [Yeasir0032/Discord-Clone#18]
### Server Explorer
A **new user** who has not been in any server can go to this page and find and join a server.

**Current scenario:**- 
Whenever a new user is created , a server create modal appears.

**Solution:**
The new user will be redirected to the server explorer page and can select and join any server.

**Overview of the solution:**
- Create a new route in app directory
- Create page.tsx file
- Get all servers from database
- Display them 
- Handle searching and joining

**Comment by Latish705** [comment]
@Yeasir0032 I would like to work on this issue

**Comment by Yeasir0032** [comment]
How much did you require for it @Latish705 ?

**Comment by Latish705** [comment]
@Yeasir0032  Maximum 1 day

**Comment by Yeasir0032** [comment]
Assigning it to you 
Deadline 12th May Midnight

**Comment by codebreaker3008** [comment]
@Yeasir0032 the issue has not been resolved yet, its 12th May Midnight, Can I work on this ?

**Comment by Latish705** [comment]
@Yeasir0032 @codebreaker3008 I am working on it I might complete till 12:00am 13 may

**Comment by Latish705** [comment]
@Yeasir0032 need a help I have created explore server page but I am facing difficulties in creating and getting server might be it using paid service for image could be please help me to understand structure and flow

**Comment by codebreaker3008** [comment]
@Yeasir0032 could you assign this to me ??

**Comment by Yeasir0032** [comment]
@Latish705 Can you show it here what you have done. 
Share the :
- app structure
- page.tsx file
I think you have misunderstood something. I don't think there is any paid service for image. Could you please elaborate on this matter

**Comment by codebreaker3008** [comment]
@Yeasir0032 I think I can do this, can you assign this to me and I would even complete it within the deadline

**Comment by Latish705** [comment]
@Yeasir0032 

https://github.com/Yeasir0032/Discord-Clone/assets/104522651/06de2361-7317-4a0e-8db7-d647c946f2d3

I have made new route whenever the user signup then it will redirected to this route then he can select the server and then can join server implemented search function

**Comment by Latish705** [comment]
the main thing I am facing is the while creating the server we might need to upload the image then upload thing is paid service

**Comment by Yeasir0032** [comment]
Please provide the code where you have implemented the image

**Comment by Latish705** [comment]
@Yeasir0032 I have commited in my fork repo 
https://github.com/Latish705/Discord-Clone

**Comment by Latish705** [comment]
@Yeasir0032 in the latest commit I have added all feature you need can you cross check in my forked repo
