### ISSUE TITLE
doc : code of conduct file should add on repo

### ISSUE THREAD

**Issue by officeneerajsaini** [Yeasir0032/Discord-Clone#22]
-  we need to add code of conduct file in repo

- Sample: [CODE_OF_CONDUCT](https://github.com/Recode-Hive/Stackoverflow-Analysis/blob/main/CODE_OF_CONDUCT.md)

**Comment by officeneerajsaini** [comment]
@Yeasir0032 assign this issue to me , and also add gssoc label /tag on issue

**Comment by Yeasir0032** [comment]
@officeneerajsaini 
There already an issue exist.
 Check here [https://github.com/Yeasir0032/Discord-Clone/issues/6](https://github.com/Yeasir0032/Discord-Clone/issues/6)

**Comment by officeneerajsaini** [comment]
@Yeasir0032  my bad
