### ISSUE TITLE
Add Contribuing.md

### ISSUE THREAD

**Issue by Yeasir0032** [Yeasir0032/Discord-Clone#23]
Add contributing.md file for the repo

**Comment by codebreaker3008** [comment]
@Yeasir0032  what would I have to do ?

**Comment by Yeasir0032** [comment]
As might you have seen a File named contributing.md file is there.
It tells the eager contributors how to contribute 
For example - [https://github.com/supabase/supabase/blob/master/CONTRIBUTING.md](https://github.com/supabase/supabase/blob/master/CONTRIBUTING.md)

**Comment by codebreaker3008** [comment]
@Yeasir0032  coulkd you assign this to me ?

**Comment by codebreaker3008** [comment]
@Yeasir0032  can you accept the merge ??
