### ISSUE TITLE
can i contrubuite any thing i know UI/UX and know next.js ,react,and tailwind css 

### ISSUE THREAD

**Issue by Venkatknight2295** [Yeasir0032/Discord-Clone#25]
can i contrubuite any thing i know UI/UX and know next.js ,react,and tailwind css @Yeasir0032

**Comment by Yeasir0032** [comment]
Absolutely Why not!! 
#### Recommended to do:
- Try the app and create user (You can do the whole setup as well)
- Here is an invite link  for a server of mine [https://discord-a.up.railway.app/invite/6258d657-1637-4a52-a752-825347e32111](https://discord-a.up.railway.app/invite/6258d657-1637-4a52-a752-825347e32111). If you want you can create your own.
- Find for bugs, glictches, ui-ux change needed
- Create an issue
#### Or you can explore [this](https://github.com/Yeasir0032/Discord-Clone/issues) section. More issues will be added soon.

**Comment by Yeasir0032** [comment]
You should ask this questions in [discussion](https://github.com/Yeasir0032/Discord-Clone/discussions) not in issues.

**Comment by Yeasir0032** [comment]
You close this issue by yourself.
