### ISSUE TITLE
Create contributors showcase in the readme file

### ISSUE THREAD

**Issue by Yeasir0032** [Yeasir0032/Discord-Clone#26]
Add a section named contributors that is a showcase for all the contributors in the repo.
Like this -
![68747470733a2f2f6d69726f2e6d656469756d2e636f6d2f6d61782f313035302f312a68626951497476797463367242704e493376466b58772e706e67](https://github.com/Yeasir0032/Discord-Clone/assets/124646897/49c7d1ba-6355-41e5-852a-41c3b8789c08)

Check for guide here [https://github.com/Tanu-N-Prabhu/myWebsite.io/blob/master/Docs/Displaying%20Contributors%20Image%20on%20README%20files%20with%20no%20Pain!.md](https://github.com/Tanu-N-Prabhu/myWebsite.io/blob/master/Docs/Displaying%20Contributors%20Image%20on%20README%20files%20with%20no%20Pain!.md)

**Comment by suhanipaliwal** [comment]
I would like to work on this issue. Please assign me this task.

**Comment by codebreaker3008** [comment]
@Yeasir0032  I have added the contributors.md file could you merge it and I would like to work on this can you assign this to me

**Comment by codebreaker3008** [comment]
@Yeasir0032  please assign me this

**Comment by Madhu-mac** [comment]
@Yeasir0032 Please assign me this issue, I would like to work on it. I'm half way done!!

**Comment by codebreaker3008** [comment]
@Yeasir0032  created the pull request, review and merge it

**Comment by codebreaker3008** [comment]
@Yeasir0032  sorry wifi was down, so had to do that again, now you can verify that
