### ISSUE TITLE
Update README for Improved Documentation

### ISSUE THREAD

**Issue by jinx-vi-0** [Yeasir0032/Discord-Clone#30]
The current README is not visually appealing and also lacks some sections like contributors. I would like to update tech stack section and also properly format the documentation.

![image](https://github.com/Yeasir0032/Discord-Clone/assets/120160355/4c60d6a6-59e6-4498-9e27-e2d61ba014e4)

**Comment by Yeasir0032** [comment]
I am assigning this to you

**Comment by hari659tri** [comment]
I want to work on this issue. Please assign me this under GSSOC24 label
