### ISSUE TITLE
Creating Dockerfile for the Discord-Clone

### ISSUE THREAD

**Issue by harshnayangithub** [Yeasir0032/Discord-Clone#34]
Is your feature request related to a problem? Please describe.
The problem is the lack of a Dockerfile for the Discord-Clone project.

Describe the solution you'd like
Implementing a Dockerfile for the Discord-Clone project to containerize the application and simplify deployment.

**Comment by harshnayangithub** [comment]
Assign it to me under gssoc'24

**Comment by Yeasir0032** [comment]
Provide steps how will you achieve this?

**Comment by harshnayangithub** [comment]
As a DevOps enthusiast, I've drafted various Dockerfile for my projects. While I haven't thoroughly reviewed the codebase, I understand the general steps required for creating a Dockerfile for any Node.js project.

I anticipate encountering challenges while crafting the Dockerfile for such a large  project, which may require troubleshooting. I believe it will take considerable amount of time for creating a Dockerfile for this project and finally reducing it's size.
Once the Dockerfile is successfully created, I plan to proceed with generating a docker-compose file for the Discord clone.
 
 Dockerfile's basic implementation

FROM ubuntu:20.04
FROM node:14-alpine
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
# Will decide it later which port to expose
EXPOSE 3000
CMD ["npm", "start"]

**Comment by KanishkChhajed** [comment]
I am interested in this issue . 
Can you assign this issue to me.

**Comment by KanishkChhajed** [comment]
@Yeasir0032 I made a pull request, can you review it for this #56 .

**Comment by Yeasir0032** [comment]
The docker file is crashing the server and the deployment
![Screenshot from 2024-05-23 15-30-45](https://github.com/Yeasir0032/Discord-Clone/assets/124646897/60c99d39-5c23-4d6b-a919-5586990ec923)

**Comment by Yeasir0032** [comment]
Considering my limited expertise in DevOps, I am contemplating the removal of the Docker file.
