### ISSUE TITLE
close icon not working

### ISSUE THREAD

**Issue by Varsani2520** [Yeasir0032/Discord-Clone#38]
**Describe the bug**
user click on close icon then it is not closed 
![image](https://github.com/Yeasir0032/Discord-Clone/assets/137641079/85684d1f-9729-4547-b5f0-dde1846d1d3f)

**Comment by Yeasir0032** [comment]
The modal is non-cancellable. 
Can you remove the close icon?

**Comment by Varsani2520** [comment]
yes .if you assign this issue then i removed it 
please assign me @Yeasir0032 
so i can remove it

**Comment by Varsani2520** [comment]
thank you @Yeasir0032  for giving me this oppertunity
