### ISSUE TITLE
Light and dark mode for user satisfaction 

### ISSUE THREAD

**Issue by ayushkamboj18** [Yeasir0032/Discord-Clone#61]
Currently the users can only use the web-app in light mode. To enhance user experience, we can add a night mode option.

Describe the solution you'd like
I want to add a light/dark mode toggle feature. This feature would allow users to switch between light and dark themes based on their preference or the ambient lighting conditions.

Additional context
This is under GSSOC'2024 Contribuition

**Comment by Yeasir0032** [comment]
The dark mode is present. Is it not working?
There is toggle button in the right bottom corner
