### ISSUE TITLE
Design a Login Page

### ISSUE THREAD

**Issue by Yeasir0032** [Yeasir0032/Discord-Clone#64]
## Just design a login page without any functionality
![Screenshot from 2024-05-23 15-06-45](https://github.com/Yeasir0032/Discord-Clone/assets/124646897/8a0af4e4-b4cf-4a5e-9485-26d2be8ff6ac)
**Make sure your design is as per the picture above**
**You should not use the same image as above for background you can take any image from unsplash, make sure that you give a url to the image**

You have to do:
- [ ] Create the page in `componets/home-layouts`
- [ ] Name the file `LoginPage`
- [ ] No need to do the QR thing
- [ ] Add `Google Login` button in place of `QR`
- [ ] Use `Tailwind css` and `Radix UI`
- [ ] Dark mode and Light mode compatibility.

**Comment by omsai11** [comment]
@RiyaRanka @aryanmehra0  @saswat733 You guys want to work on this feature updation

**Comment by RiyaRanka** [comment]
@omsai11 I can work on  this feature. I will create the Login page using Tailwind CSS. Please assign me this issue.

**Comment by Yeasir0032** [comment]
@RiyaRanka 
Are you able to work with
- [ ] Radix UI
- [ ] Themeing in Tailwind 
- [ ] JSX

**Comment by saswat733** [comment]
@Yeasir0032  i am not able to setup your project i am following your readme but still not able to do it can you please guid me i am getting some errors

**Comment by Yeasir0032** [comment]
@saswat733 
I think the supabase is not setup properly 
I mean the tables and everything 
I am working on it.
What is your error by the way?

**Comment by RiyaRanka** [comment]
Yes I am will work with:
> * [X]  Radix UI
> * [X]  Themeing in Tailwind
> * [X]  JSX

**Comment by parthiv011** [comment]
Is this issue still open if not Can i work?

**Comment by parthiv011** [comment]
Hi @Yeasir0032 I am recieving this error while setting up the project can u help me with it?
Says Unhandled Runtime Error
Error: destination url or return back url should be an absolute path url!

![Screenshot (175)](https://github.com/Yeasir0032/Discord-Clone/assets/118474748/51418a88-b1ea-4fbc-876a-4d43178d3c8b)

**Comment by Yeasir0032** [comment]
I think it's a Clerk Js error 
Make sure you setup properly

**Comment by parthiv011** [comment]
> I think it's a Clerk Js error 
> Make sure you setup properly 

This I am receiving after I signin using Google in clerk 
It also shows the user in clerk dashboard.

**Comment by KanishkChhajed** [comment]
Hey @parthiv011 how can you solve that 

> Hi @Yeasir0032 I am recieving this error while setting up the project can u help me with it? Says Unhandled Runtime Error Error: destination url or return back url should be an absolute path url!
> 
> Though I have setup all the urls in .env file
> 
> ![Screenshot (175)](https://private-user-images.githubusercontent.com/118474748/335820917-51418a88-b1ea-4fbc-876a-4d43178d3c8b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI3OTI1OTIsIm5iZiI6MTcyMjc5MjI5MiwicGF0aCI6Ii8xMTg0NzQ3NDgvMzM1ODIwOTE3LTUxNDE4YTg4LWIxZWEtNGZiYy04NzZhLTRkNDMxNzhkM2M4Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgwNFQxNzI0NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYzFmZGY1NDIyNjZlNzc1M2IwZmU4NTg1YWFjZTYwZWQwN2ZlZWQ2NjgxYTJiZDc4NzAxZjZkNzJhMjcwZGY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5YkXEDPaP5rpAJhCemq33qwSQs9phLucO-sEP3ni0qI)

Hey @parthiv011 @PayalKumari10, how can you solve this problem? Could you tell me the steps to solve this issue, as I am also currently facing this issue?

**Comment by PayalKumari10** [comment]
@KanishkChhajed, Can you tell me what type of error you are facing? Expalin it.

**Comment by KanishkChhajed** [comment]
Hello @PayalKumari10, Basically I am facing two types of problem :
1. When I sign in as a new user, maybe there is no set callback page in it, as result I got this error:
  ![Screenshot 2024-08-05 075753](https://github.com/user-attachments/assets/b61ca24e-d7ed-4db8-ac88-22d9afb466f1)

2. When I have already signed in as a user, then run the project, I got this problem:
![Screenshot 2024-08-05 080545](https://github.com/user-attachments/assets/1d80444a-95f7-4285-a88f-9b7809188ab0)

I think there is no problem with clerk JS as new user instance is created there and this is middleware related problem.
I am unable to fix this right now, please help me out with this.

**Comment by Yeasir0032** [comment]
Hey @KanishkChhajed could you please create a new issue for this bug.
It would be greatly helpful

**Comment by KanishkChhajed** [comment]
Hey @Yeasir0032, I'm going to create a new issue for this.
