### ISSUE TITLE
Add a button for server explorer in navigation bar

### ISSUE THREAD

**Issue by Yeasir0032** [Yeasir0032/Discord-Clone#68]
## Adding server explorer button in navigation bar
We have to add a button inside of navigation bar that opens the route for Server explorer page.
Steps to do:

- Go to `components/navigation/navigation-sidebar.tsx`
- Add a button in line number 24
```html
<div className="space-y-4 flex flex-col items-center h-full bg-[#e3e5e8] text-primary w-full dark:bg-[#1e1f22] py-3">
      <NavigationAction />
      {\* We have create the button here */}
      <Separator className="h-[2px] bg-zinc-300 rounded-md mx-auto w-10" />
``` 
- Here Navigation Action is a button that creates a server We just have to create one like that 
- No need to create another component , you can just do it here
- No need to handle click events
- Use icons from lucide react or just paste a svg

### Current scenario
![Screenshot from 2024-05-24 19-43-13](https://github.com/Yeasir0032/Discord-Clone/assets/124646897/56b22d65-8e41-41fe-8608-a3b8f5f8f8bb)
### Final scenario needed
![Screenshot from 2024-05-24 19-43-28](https://github.com/Yeasir0032/Discord-Clone/assets/124646897/686bcb6d-6ff3-444f-8adf-3bc14960f2b8)

**Comment by Devank-Sachdeva** [comment]
I will be happy to take this issue please assign it to me

**Comment by Yeasir0032** [comment]
Good Luck @Devank-Sachdeva  mate. If you encounter any problem feel free to ask.
