### ISSUE TITLE
Auto commenting feature for new PR raised 

### ISSUE THREAD

**Issue by suhanipaliwal** [Yeasir0032/Discord-Clone#71]
This feature aims to address the problem of delayed and inconsistent communication following the raising of PRs. By automatically commenting on PRs as soon as they are raised, it ensures that contributors receive immediate feedback and acknowledgment for their efforts. This fosters a positive and supportive environment for collaboration, encouraging continued participation and engagement from contributors.

Could you please assign me this issue under GSSOC'24.

**Comment by Yeasir0032** [comment]
There is an action that provides a welcome message are you saying about that?

**Comment by suhanipaliwal** [comment]
> There is an action that provides a welcome message are you saying about that? @suhanipaliwal

That welcome message is displayed only on the first pull request of a contributor. The pull request sent above will add a comment on every pr raised.
