### ISSUE TITLE
Automate the task to manually create database structure using supabase migration

### ISSUE THREAD

**Issue by Devank-Sachdeva** [Yeasir0032/Discord-Clone#79]
**Is your feature request related to a problem? Please describe.**
As of now, even to start the project we have to manually create the table schema in supabase dashboard by executing SQL commands provided in table_setup.md. And even after that to test a functionality we have to manually create table entries which is very inconvenient and delays meaningful time which could have been focused on development

**Describe the solution you'd like**
We can automate the above process my using [migrations](https://supabase.com/docs/reference/cli/supabase-migration) 
just by executing few commands like 

Links the current project with the supabase project
``` 
npx supabase link --project-ref <Project-id>
```

Migrate the Supabase database to the desired structure defined in table_setup.md
```
npx supabase db push
```

we can seed the data (filling the table with sample data) after the tables have migrated using [seeding](https://supabase.com/docs/guides/cli/seeding-your-database)

**Additional context**
All of the above will speedup the process of setting up the project locally

**Comment by Devank-Sachdeva** [comment]
I will be happy to build this functionality for the project

**Comment by Yeasir0032** [comment]
Thanks for pointing it out.
Good luck
@Devank-Sachdeva
